### ISSUE TITLE
How do I run the code on Mac?

### ISSUE THREAD

**Issue by bikedel** [Palexer/image-viewer#2]
Homes-iMac:ImageViewer home$ go build main.go
# command-line-arguments
./main.go:58:13: undefined: Img
./main.go:98:10: undefined: Img
./main.go:135:12: undefined: resourceIconPng
./main.go:136:12: undefined: resourceIconPng
./main.go:139:17: ui.loadMainUI undefined (type *App has no field or method loadMainUI)
./main.go:145:5: ui.open undefined (type *App has no field or method open)

**Comment by AbdulAhadAkhter** [comment]
Hey hi just curious if you figured out what was causing this issue? I'm facing the same error using go 1.19.

**Comment by bikedel** [comment]
Hello

Yes I did figure it out and built quite a bit on top. This was sooo long ago I really don’t recall.



I have currently got   go1.15 installed so it works with that.
 


It may have something to do will your build command…. you need to add all the files like below.

go run main.go ui.go img.go fileio.go template.go gifted.go  bundled.go settings.go database.go template2.go


Help this helps.

What are you building? What made you choose Fine?


Regards
Paul




h

**Comment by AbdulAhadAkhter** [comment]
ah okay I'll give that a try! Thank you! 

I picked up golang for work a couple years ago. Recently I just wanted to try building some desktop apps (simple notes editor, image previewer, etc) and fyne looked like it fit the bill compared to wails or go-app.

Just curious what features did you end up adding on top of this base project?

**Comment by bikedel** [comment]
I have thousands of unsorted Canon 5D images. Sorted by date in folders. Each folder contains up to 2000 images.

I added  an sqlite backend so if I open a folder all the images gets stored in the database. I can then rate them, categorise them, add tags, add attributes….. nice and simple and I do it on the fly and when I get the chance. But I had to give up and find better solutions.

Some nice little features to step through my folders with next, previous, random  buttons. Easily change some basics like brightness , contrast…..and apply filters. I must add it is a bit slow compared to js to do image manipulation.



I  can chose to use either a folder of a database search and create different style mosaics  from the supplied images. So auto generating new content. Maybe video clips etc…...

I wanted more AI detection.. auto classify…. I was looking into doing annotations, …..


But I gave up on Fyne…wails…... I now use vue3 Quasar and some libraries and am much happier. I can crate desktop apps, mobile web……… pwa…..

**Comment by AbdulAhadAkhter** [comment]
Ah okay. I'll take a look at quasar too. Haven't heard much about it. Just got into gui frameworks.

**Comment by bikedel** [comment]
I have not looked at Fyne for a while. Are you able to deploy your app as a webpage?

What country, city are you in? Cape Town, South Africa here.

**Comment by AbdulAhadAkhter** [comment]
Apologies, got swamped with life and layoffs. Guess I couldn't dodge the inevitable. I believe there is the ability to run it within the browser now but it's renders extremely slowly for now.  

I'm currently located in Niagara Falls Ontario Canada.

**Comment by bikedel** [comment]
so now you are your own boss! cool

maybe we can work on a project together?

**Comment by AbdulAhadAkhter** [comment]
Yes! I would love to hop on a call some day!

**Comment by bikedel** [comment]
I don’t hop on calls at the moment.  don’t even know what it is. I don’t use cell phone or video. 

You have a problem and I fix it. If you have an idea and /I like it I will work for free. I am a fullnstack developer.  But we are in opposing parts of the globe and there could be a trade?



I had good times at Niagra falls!  I think I also covered every inch of toronto with roller blades.


Are you open to ideas?


Regards
\Pau,

**Comment by AbdulAhadAkhter** [comment]
Ah okay understandable. Timezone shouldn't be a problem since I've almost always worked async haha 😅 I'm just going through job applications atm. 

Yes absolutely open to ideas!  

Feel free to ping me on my other socials (on my github profile) and maybe we can get started exchanging ideas?

At the moment I'm thinking of building out a quick transcoding tool that allows users to encode any video file with ffmpeg to prores/dnxhd for easier editing in video software. One of the stretch goals I have is to allow ffmpeg to use plugins for stuff like denoising and filters. I have a cli already built that does the transcoding. Just figuring out how the plugin ecosystem works in ffmpeg.
