### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by bikedel** [Palexer/image-viewer#8]
Hi,

It would be great to be able to see thumbnails of the directory. Infinite scroll or paging.

In my use case I could have 2000+ cannon DSLR images in a folder. 3mb + each.

I tried a very crude implementation but it was way to slow. Almost workable if I paged the thumbnails to say show 12 at a time. Thumbnails created on the fly. I did find a fyne implementation of showing thumbnails of large images on the fly that used MD5 and caching..... lightning fast.

**Comment by Palexer** [comment]
Could you give me a link to the Fyne thumbnail implementation or just make a pull request with it?

**Comment by bikedel** [comment]
https://github.com/okratitan/fyfoto

It is lightning fast to start and then kinda grinds to a halt after viewing a few big folders.... I have not had an in depth look at what is going on... but was very impressed. I imagine if instead of infinite scroll a paging approach is used it would work for my scenario of having many folders with many images of a large size.
